'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {createQirService,episode}=require('../../lib/qir/service');
const transcript=require('../../public/qir-transcript');
const id='dd4c4188-f5f7-4a19-abd2-c4ede0735912';
const raw={public_id:id,show_key:'demo',show_name:'Demo',title:'Demo',headline:'Housing',summary:'Sample test summary',host:null,guest:null,category:'Public Affairs',air_date:'2026-09-18',air_start:'12:00:00',air_end:'13:00:00',duration_minutes:60,mp3_url:'https://archive.kpfk.org/mp3/example.mp3',updated_at:'2026-09-18T03:27:27Z'};
const json=data=>new Response(JSON.stringify(data),{headers:{'content-type':'application/json'}});
function provider(extra={}) {const calls=[];let page=0;const fetchImpl=async(url,options)=>{calls.push({url,headers:options.headers});if(url.endsWith('/shows'))return json({shows:[{key:'demo',show_group:'Demo',display_name:'Demo',category:'News',active:true}]});if(url.includes('/transcript'))return json({transcript:'A transcript',vtt:'WEBVTT\n\n00:00.000 --> 00:04.000\nHello'});page++;return json({data:[{...raw,headline:page===1?'Old':'Corrected'}],next_cursor:page===1?'opaque cursor':null});};return {calls,service:createQirService({enabled:true,key:'secret-test',fetchImpl,minIntervalMs:0,...extra})};}
test('missing credentials and disabled plugin never call provider or expose key',async()=>{let calls=0;const s=createQirService({enabled:true,fetchImpl:()=>{calls++;}});await assert.rejects(s.catalog(),/not_configured/);assert.equal(calls,0);assert.equal(s.status().state,'not_configured');const d=createQirService({key:'private',enabled:false});assert.doesNotMatch(JSON.stringify(d.status()),/private/);await assert.rejects(d.catalog(),/not_configured/);});
test('opaque pagination, id upserts, shared cache and transcript projection',async()=>{const {service,calls}=provider();const [a,b]=await Promise.all([service.catalog(),service.catalog()]);assert.deepEqual(a,b);assert.equal(a.episodes.length,1);assert.equal(a.episodes[0].headline,'Corrected');assert.ok(calls.some(c=>c.url.includes('cursor=opaque%20cursor')));assert.equal(calls.length,3);assert.equal(calls[0].headers.Authorization,'Bearer secret-test');assert.doesNotMatch(JSON.stringify(a),/secret-test/);assert.equal((await service.transcript(id)).transcript,'A transcript');await service.transcript(id);assert.equal(calls.length,4);await assert.rejects(service.transcript('../bad'),/invalid_episode_id/);});
test('failed refresh keeps last-good data explicitly stale and backs off',async()=>{let now=1000,fail=false,calls=0;const s=createQirService({enabled:true,key:'key',now:()=>now,minIntervalMs:0,ttlMs:100,fetchImpl:async url=>{calls++;if(fail)return new Response('no',{status:429,headers:{'retry-after':'60'}});return json(url.endsWith('/shows')?{shows:[]}:{data:[raw],next_cursor:null});}});await s.catalog();now+=101;fail=true;const stale=await s.catalog();assert.equal(stale.stale,true);assert.equal(stale.episodes[0].public_id,id);const count=calls;await s.catalog();assert.equal(calls,count);});
test('redirects are never followed with bearer credentials',async()=>{let calls=0;const s=createQirService({enabled:true,key:'key',minIntervalMs:0,fetchImpl:async()=>{calls++;return new Response('',{status:302,headers:{location:'https://elsewhere.example/'}});}});await assert.rejects(s.catalog());assert.equal(calls,1);});
test('unsafe audio URL and repeated cursor cannot publish a catalog',async()=>{for(const mode of ['audio','cursor']){const s=createQirService({enabled:true,key:'key',minIntervalMs:0,fetchImpl:async url=>json(url.endsWith('/shows')?{shows:[]}:{data:[{...raw,mp3_url:mode==='audio'?'https://unknown.example/audio':raw.mp3_url}],next_cursor:mode==='cursor'?'same':null})});await assert.rejects(s.catalog());assert.equal(s.status().lastSuccess,null);}});
test('transcript 404 stays distinct from provider outage',async()=>{const s=createQirService({enabled:true,key:'key',minIntervalMs:0,fetchImpl:async url=>url.includes('/transcript')?new Response('',{status:404}):json(url.endsWith('/shows')?{shows:[]}:{data:[raw],next_cursor:null})});await assert.rejects(s.transcript(id),e=>e.status===404);assert.equal(s.status().state,'ready');});
test('VTT cues retain speaker labels, reject invalid timing, and are data not HTML',()=>{const cues=transcript.parse('WEBVTT\n\n1\n00:01.000 --> 00:04.000\n<v Speaker 2>Hello <b>world</b>\n\n00:05.000 --> 00:03.000\nBad\n\n00:08.000 --> 00:40.000\nOutside',10);assert.deepEqual(cues,[{start:1,end:4,text:'Speaker 2: Hello world'}]);assert.deepEqual(transcript.parse('Not VTT',10),[]);});

test('invalid station-local dates and times cannot enter the beta catalog',()=>{
 for(const fields of [{air_date:'2026-02-30'},{air_start:'99:10:00'},{air_start:'12:70:00'}])assert.throws(()=>episode({...raw,...fields},['https://archive.kpfk.org']),/invalid_episode_time/);
});
